spring:
  datasource:
    url: jdbc:postgresql://postgresqldb:5432/kartacadb
    username: admin
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'false'
    hibernate:
      ddl-auto: update

kafka:
  brokers: kafka:9092
server:
  port: 8080